version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # You can specify your required Node.js version here
    commands:
      - echo Installing dependencies...
      - npm install  # Install dependencies

  build:
    commands:
      - echo Running build...
      - npm run build  # Run your build process (only if needed)

  post_build:
    commands:
      - echo Running tests...
      - npm test  # Run tests using your defined test command

  deploy:
    commands:
      - echo Deploying to AWS Amplify...
      - npm install -g @aws-amplify/cli  # Install the Amplify CLI
      - amplify status  # Check the status of your Amplify app
      - amplify push  # Deploy the app to AWS Amplify




