version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1" # Set the AWS Region
    REPOSITORY_NAME: "myrepo/cicd" # ECR repository name
    GITHUB_REPO: "https://github.com/Rahuljondhale853/nodejs" # GitHub repository
    AWS_ACCOUNT_ID: "337909742643" # AWS Account ID
    REPOSITORY_URI: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME" # ECR repository URI

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies and preparing Docker environment..."
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  pre_build:
    commands:
      - echo "Setting environment variables..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7) # Short Git commit hash for the image tag
      - echo "Image tag is $IMAGE_TAG"
      - echo "Repository URI is $REPOSITORY_URI"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
