version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # You can specify your required Node.js version here
    commands:
      - echo Installing dependencies...
      - npm install  # Install dependencies

  build:
    commands:
      - echo Running build...
      - npm run build  # Run your build process (only if needed)

  post_build:
    commands:
      - echo Running tests...
      - npm test  # Run tests using your defined test command

cache:
  paths:
    - 'node_modules/**/*'  # Cache node_modules to speed up future builds


